version: "3.3"
services:
  # API:
  #   build: ./BackEnd
  #   ports:
  #     - "8000:5000"
  #   volumes:
  #     - .:/code
  #   environment:
  #     FLASK_ENV: development
  # services:

  mongo:
    image: mongo
    container_name: container-mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    image: mongo-express
    container_name: container-mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: exemple